const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const MARKER = "# @generated by withIosNonModularHeaders";

const PATCH_LINES = [
	`  ${MARKER}`,
	"  installer.pods_project.targets.each do |target|",
	"    target.build_configurations.each do |config|",
	"      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'",
	"    end",
	"  end",
];

function findPostInstallEndLine(lines, startIndex) {
	let depth = 0;

	for (let i = startIndex; i < lines.length; i += 1) {
		const line = lines[i].trim();

		if (line.match(/\bdo\b/)) {
			depth += 1;
		}

		if (line === "end") {
			depth -= 1;

			if (depth === 0) {
				return i;
			}
		}
	}

	return -1;
}

function withIosNonModularHeaders(config) {
	return withDangerousMod(config, [
		"ios",
		async (config) => {
			const podfilePath = path.join(
				config.modRequest.platformProjectRoot,
				"Podfile"
			);

			if (!fs.existsSync(podfilePath)) {
				return config;
			}

			let podfile = fs.readFileSync(podfilePath, "utf8");

			if (podfile.includes(MARKER)) {
				return config;
			}

			const lines = podfile.split("\n");

			const postInstallStart = lines.findIndex((line) =>
				line.includes("post_install do |installer|")
			);

			if (postInstallStart === -1) {
				lines.push("");
				lines.push("post_install do |installer|");
				lines.push(...PATCH_LINES);
				lines.push("end");

				fs.writeFileSync(podfilePath, lines.join("\n"));
				return config;
			}

			const postInstallEnd = findPostInstallEndLine(lines, postInstallStart);

			if (postInstallEnd === -1) {
				throw new Error(
					"Não foi possível encontrar o end do bloco post_install no Podfile."
				);
			}

			lines.splice(postInstallEnd, 0, ...PATCH_LINES);

			fs.writeFileSync(podfilePath, lines.join("\n"));

			return config;
		},
	]);
}

module.exports = withIosNonModularHeaders;